/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.workforceai.controller; import cn.zhuatech.workforceai.common.ApiResponse; import cn.zhuatech.workforceai.dto.WorkforceAiDto.*; import cn.zhuatech.workforceai.service.WorkforceAiService; import cn.zhuatech.workforceai.service.AiRiskAssessmentService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/shopfloor") @PreAuthorize("hasAnyRole('DOMAIN_USER','ADMIN')") public class WorkspaceController {private final WorkforceAiService service;private final AiRiskAssessmentService risk;/**
                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                            */
public WorkspaceController(WorkforceAiService service,AiRiskAssessmentService risk){this.service=service;this.risk=risk;}/**
                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                     */
@GetMapping("/dashboard") public ApiResponse<Dashboard> dashboard(){return ApiResponse.ok(service.shopfloorDashboard());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/work-orders/{id}/reports") public ApiResponse<ReportResult> report(@PathVariable Long id,@Valid @RequestBody ReportRequest request){return ApiResponse.ok("会话智能质检反馈已提交",service.report(id,request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/ai-risk-assessment") public ApiResponse<AiRiskAssessmentService.Result> assess(@Valid @RequestBody AiRiskAssessmentService.Request request){return ApiResponse.ok("AI 风险评估完成",risk.assess(request));}}
